###
GET http://localhost:8080/healthy

###
GET http://localhost:8080/categories

###
POST http://localhost:8080/categories
Content-Type: application/json

{
    "name": "Technology"
}


###
GET http://localhost:8080/categories/2

###
PATCH http://localhost:8080/categories/2
Content-Type: application/json

{
    "name": "Docker"
}

###
DELETE http://localhost:8080/categories/2